MAINT: remove __init__ method from BaseMetricLearner
Since it is an abstract class it already returns an error at instanciation:
TypeError: Can't instantiate abstract class BaseMetricLearner with abstract methods score_pairs